version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: iliksu-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iliksukardesler
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    container_name: iliksu-elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"